# 服务器配置
[server]
host = "0.0.0.0"
port = 8080

# 数据库配置
[database]
driver = "mysql"
username = "root"
password = "Dhrsny678bjsfb@!"
host = "117.78.2.33"
port = 3306
name = "TicketTrain"
max_connections = 100

# 缓存配置
[cache]
type = "redis"
host = "117.78.2.33"
port = 6379
password = "123456"
max_idle_connections = 100
max_active_connections = 500

# 日志配置
[log]
level = "info"
path = "/Users/tal/go/goTrain/log/train.log"