// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: order_tickets.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddOrderTicketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId  int64 `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	TicketId int64 `protobuf:"varint,2,opt,name=TicketId,proto3" json:"TicketId,omitempty"`
}

func (x *AddOrderTicketReq) Reset() {
	*x = AddOrderTicketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_tickets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOrderTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderTicketReq) ProtoMessage() {}

func (x *AddOrderTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_tickets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderTicketReq.ProtoReflect.Descriptor instead.
func (*AddOrderTicketReq) Descriptor() ([]byte, []int) {
	return file_order_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderTicketReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AddOrderTicketReq) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type DelOrderTicketReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId  int64 `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	TicketId int64 `protobuf:"varint,2,opt,name=TicketId,proto3" json:"TicketId,omitempty"`
}

func (x *DelOrderTicketReq) Reset() {
	*x = DelOrderTicketReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_tickets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelOrderTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOrderTicketReq) ProtoMessage() {}

func (x *DelOrderTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_tickets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOrderTicketReq.ProtoReflect.Descriptor instead.
func (*DelOrderTicketReq) Descriptor() ([]byte, []int) {
	return file_order_tickets_proto_rawDescGZIP(), []int{1}
}

func (x *DelOrderTicketReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DelOrderTicketReq) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

type GetOTDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
}

func (x *GetOTDetailReq) Reset() {
	*x = GetOTDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_tickets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOTDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTDetailReq) ProtoMessage() {}

func (x *GetOTDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_tickets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTDetailReq.ProtoReflect.Descriptor instead.
func (*GetOTDetailReq) Descriptor() ([]byte, []int) {
	return file_order_tickets_proto_rawDescGZIP(), []int{2}
}

func (x *GetOTDetailReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOTDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId    int64  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	TicketId   int64  `protobuf:"varint,2,opt,name=TicketId,proto3" json:"TicketId,omitempty"`
	CreateTime string `protobuf:"bytes,3,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime string `protobuf:"bytes,4,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
}

func (x *GetOTDetailResp) Reset() {
	*x = GetOTDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_tickets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOTDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTDetailResp) ProtoMessage() {}

func (x *GetOTDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_tickets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTDetailResp.ProtoReflect.Descriptor instead.
func (*GetOTDetailResp) Descriptor() ([]byte, []int) {
	return file_order_tickets_proto_rawDescGZIP(), []int{3}
}

func (x *GetOTDetailResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOTDetailResp) GetTicketId() int64 {
	if x != nil {
		return x.TicketId
	}
	return 0
}

func (x *GetOTDetailResp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GetOTDetailResp) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

var File_order_tickets_proto protoreflect.FileDescriptor

var file_order_tickets_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x49, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x49, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f,
	0x54, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x54, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xc2,
	0x01, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x44, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x30, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4f, 0x54, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x54, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x54, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_order_tickets_proto_rawDescOnce sync.Once
	file_order_tickets_proto_rawDescData = file_order_tickets_proto_rawDesc
)

func file_order_tickets_proto_rawDescGZIP() []byte {
	file_order_tickets_proto_rawDescOnce.Do(func() {
		file_order_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_tickets_proto_rawDescData)
	})
	return file_order_tickets_proto_rawDescData
}

var file_order_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_order_tickets_proto_goTypes = []interface{}{
	(*AddOrderTicketReq)(nil), // 0: AddOrderTicketReq
	(*DelOrderTicketReq)(nil), // 1: DelOrderTicketReq
	(*GetOTDetailReq)(nil),    // 2: GetOTDetailReq
	(*GetOTDetailResp)(nil),   // 3: GetOTDetailResp
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_order_tickets_proto_depIdxs = []int32{
	0, // 0: OrderTicketService.AddOrderTicket:input_type -> AddOrderTicketReq
	1, // 1: OrderTicketService.DelOrderTicket:input_type -> DelOrderTicketReq
	2, // 2: OrderTicketService.GetOTDetail:input_type -> GetOTDetailReq
	4, // 3: OrderTicketService.AddOrderTicket:output_type -> google.protobuf.Empty
	4, // 4: OrderTicketService.DelOrderTicket:output_type -> google.protobuf.Empty
	3, // 5: OrderTicketService.GetOTDetail:output_type -> GetOTDetailResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_tickets_proto_init() }
func file_order_tickets_proto_init() {
	if File_order_tickets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_tickets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOrderTicketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_tickets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelOrderTicketReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_tickets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOTDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_tickets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOTDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_tickets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_tickets_proto_goTypes,
		DependencyIndexes: file_order_tickets_proto_depIdxs,
		MessageInfos:      file_order_tickets_proto_msgTypes,
	}.Build()
	File_order_tickets_proto = out.File
	file_order_tickets_proto_rawDesc = nil
	file_order_tickets_proto_goTypes = nil
	file_order_tickets_proto_depIdxs = nil
}
